[project]
name = "shadow-protocol"
version = "0.1.0"

[network]
cluster_offset = 0
rpc_url = "https://devnet.helius-rpc.com"
localnet_rpc_url = "http://127.0.0.1:8899"

[programs.shadow-protocol]
address = ""
program = "packages/programs/shadow-protocol/target/deploy/shadow_protocol.so"
idl = "apps/web/src/idl/shadow_protocol.json"

[provider]
cluster = "devnet"
wallet = "/home/vivek/projects/shadow/shadow-protocol/deployer-keypair.json"

[arcium]
endpoint = "https://testnet-api.arcium.com"

[test]
startup_wait = 10000
shutdown_wait = 2000