[package]
name = "encrypted-ixs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
arcis-imports = { workspace = true }
arcium-macros = { workspace = true }
arcium-anchor = { workspace = true }
arcis = "0.1.47"