[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
shadow_protocol_confidential = "DWrCjVyfhysTNwQh96PzScBAiCvZ3hAKWYfyHWpQqee8"

[programs.devnet]
shadow_protocol_confidential = "DWrCjVyfhysTNwQh96PzScBAiCvZ3hAKWYfyHWpQqee8"

[programs.mainnet]
shadow_protocol_confidential = "DWrCjVyfhysTNwQh96PzScBAiCvZ3hAKWYfyHWpQqee8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "../programs/program-keypair.json"

[scripts]
test = "echo 'No tests'"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = true

[workspace]
members = []