[package]
name = "shadow-protocol-confidential"
version = "0.1.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
shadow_protocol = "DWrCjVyfhysTNwQh96PzScBAiCvZ3hAKWYfyHWpQqee8"

[programs.devnet]
shadow_protocol = "DWrCjVyfhysTNwQh96PzScBAiCvZ3hAKWYfyHWpQqee8"

[provider]
cluster = "devnet"
wallet = "../programs/program-keypair.json"

[scripts]
test = "yarn test"

[workspace]
members = [
    "confidential-ixs"
]