[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
shadow_protocol = "GEK3zgEitHAE2djxDtSxi3Pm67kgAzTnLbMRfRurWiSK"

[programs.devnet]
shadow_protocol = "GEK3zgEitHAE2djxDtSxi3Pm67kgAzTnLbMRfRurWiSK"

[programs.mainnet]
shadow_protocol = "GEK3zgEitHAE2djxDtSxi3Pm67kgAzTnLbMRfRurWiSK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/home/vivek/projects/shadow/shadow-protocol/deployer-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = true

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/fixtures/metadata.so"

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
clone = [
    { address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA", filename = "spl_token.so" },
    { address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL", filename = "spl_associated_token.so" },
]

[workspace]
members = [
    "programs/*"
]

[build]
test-bpf = "cargo test-bpf"