[package]
name = "shadow-protocol"
version = "0.1.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
shadow_protocol = "DWrCjVyfhysTNwQh96PzScBAiCvZ3hAKWYfyHWpQqee8"

[programs.devnet]
shadow_protocol = "DWrCjVyfhysTNwQh96PzScBAiCvZ3hAKWYfyHWpQqee8"

[provider]
cluster = "devnet"
wallet = "./program-keypair.json"
cluster_offset = 2326510165

[scripts]
test = "echo 'No tests'"

[workspace]
members = []