[workspace]
members = [
    "programs/shadow-protocol",
    "encrypted-ixs"
]
resolver = "2"

# Dependency overrides to fix compatibility issues
[workspace.dependencies]
# Force specific versions of problematic dependencies
miniz_oxide = { version = "0.7", default-features = false }
brotli = { version = "6.0", default-features = false }
zstd-sys = { version = "2.0", default-features = false }
# Force all getrandom versions to use 0.2 with custom features
getrandom = { version = "0.2", features = ["custom"] }


[profile.release]
overflow-checks = true
lto = "thin"
codegen-units = 1
opt-level = "z"
strip = true

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1

